apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-eval
spec:
  template:
    spec:
      containers:
        - name: eval
          image: lukoprych/mnist-eval:1.0.3
          volumeMounts:
            - name: mnist-data
              mountPath: /data
          command: ["python", "main.py"]
      restartPolicy: Never
      volumes:
        - name: mnist-data
          persistentVolumeClaim:
            claimName: mnist-pvc